### ISSUE TITLE
typo issue in one md file.

### ISSUE THREAD

**Issue by hobbytp** [yunlzheng/prometheus-book#1]
In prometheus-book/exporter/custom_app_support_prometheus.md

please change "Sring" to "Spring" in this title.

Hobby

**Comment by yasongxu** [comment]
> “同时Prometheus还提供了一个独立的基于Ruby On Rails的Dashboard解决方案Promdash。

这个Promdash官方是不是已经没有了？

**Comment by yunlzheng** [comment]
@yasongxu https://github.com/prometheus-junkyard/promdash
