### ISSUE TITLE
邮件告警resolved中{{ $labels.value }}的值不是恢复后的值,这个怎么解决呢

### ISSUE THREAD

**Issue by wutianya** [yunlzheng/prometheus-book#11]
### 告警邮件
**[1] Firing**
**Labels**
alertname = NodeCpuUsage
environment = infra
instance = 172.17.11.5:9100
type = cpu
**Annotations**
description = CPU使用率大于80%,当前值: 100%
summary = 172.17.11.5:9100 CPU故障Source

### 恢复邮件
**[1] Resolved**
**Labels**
alertname = NodeCpuUsage
environment = infra
instance = 172.17.11.5:9100
type = cpu
**Annotations**
description = CPU使用率大于80%,当前值: 100%
summary = 172.17.11.5:9100 CPU故障

附配置文件
rules:
    groups:
    - name: os-cpu
      rules:
      - alert: NodeCpuUsage
        expr: ceil (100 - (avg(irate(node_cpu{mode='idle'}[5m])) by (instance) * 100)) > 90
        for: 1m
        labels:
          type: "cpu"
        annotations:
          summary: "{{ $labels.instance }} CPU故障"
          description: "CPU使用率大于90%,当前值: {{ $value}}%"
这个问题,困扰好久...

**Comment by yunlzheng** [comment]
resolve这部分配置实际上都是在Alertmanager部分设置的，resolve_timeout时间以后Prometheus的告警没有更新就认为告警已经恢复，所以和Prometheus里面采集的当前值不会产生关系。 抱歉，之前没注意看到有提问。

**Comment by yunlzheng** [comment]
这个之前没主要看到消息，关于这块。 先明确一点，告警的resolved状态并不是Prometheus那边处理的。 而是基于Alertmanager的resolve_timeout来实现的。所以resolved时发送的消息的内容一定是Prometheus最后更新的那次告警。

**Comment by wutianya** [comment]
谢谢大佬解惑,我有点明白了

**Comment by linhuisheng** [comment]
> 谢谢大佬解惑,我有点明白了

请问一下，你这边解决了吗？恢复后的值能否显示在模板里？

**Comment by TroubleJin** [comment]
> > 谢谢大佬解惑，我有点明白了
> 
> 好像一下，你有什么反应？恢复后的值能不能显示在模板里？

可以解决这个问题吗？

**Comment by Gaozizhong** [comment]
https://blog.csdn.net/qq_43684922/article/details/131140525这个文章说的挺好，如果显示当前值的话应该需要修改prometheus和alertmanager的源码
