### ISSUE TITLE
如何计算当前指标与5分钟之前的差值？

### ISSUE THREAD

**Issue by ghost** [yunlzheng/prometheus-book#21]
我想监控某个指标的波动率，如计算CPU使用率当前使用率跟5分钟前的对比，这个差值大于多少或者百分之多少时报警，这个是有内置函数来实现，还是要用prometheus SQL来计算二者的差值？

**Comment by lch0000** [comment]
https://prometheus.io/docs/prometheus/latest/querying/functions/#delta
