### ISSUE TITLE
是否能监控windows下tomcat服务？

### ISSUE THREAD

**Issue by captaingoodguy** [yunlzheng/prometheus-book#22]
只找到了jmx-exporter linux版本，在windows里使用的时候出现了一些错误。
![1551248400 1](https://user-images.githubusercontent.com/34262723/53539355-3d174800-3b4c-11e9-89fe-8edb45e95750.jpg)

另外，如果只监控服务是否运行 端口是否监听可以使用blackbox_exporter（windows） ，有相关的安装文档吗？

**Comment by yunlzheng** [comment]
只监控服务可用性的话 Blackbox Exporter就够了，官方的Release里面包含了windows的安装包https://github.com/prometheus/blackbox_exporter/releases/tag/v0.13.0
具体使用可以参考：https://github.com/yunlzheng/prometheus-book/blob/master/exporter/install_blackbox_exporter.md
