### ISSUE TITLE
执行不起来，什么原因

### ISSUE THREAD

**Issue by bobo200128** [yunlzheng/prometheus-book#28]
-bash: /usr/local/bin/node_exporter: cannot execute binary file

**Comment by jason0bourne** [comment]
原因：链接对应的文件是Windows系统的版本  curl -OL https://github.com/prometheus/node_exporter/releases/download/v0.15.2/node_exporter-0.15.2.darwin-amd64.tar.gz
在Linux环境执行会抛出  -bash: /usr/local/bin/node_exporter: cannot execute binary file
解决办法：
下载Linux版本的文件：node_exporter-0.17.0.linux-amd64.tar.gz
curl -OL https://github.com/prometheus/node_exporter/releases/download/v0.17.0/node_exporter-0.17.0.linux-amd64.tar.gz

**Comment by bobo200128** [comment]
下载错版本了 我发现了
