### ISSUE TITLE
使用手机微信 GitHub 小程序便捷查看该教程

### ISSUE THREAD

**Issue by ZhuPeng** [yunlzheng/prometheus-book#30]
Hi, 最近开发了一个 GitHub 的微信小程序，可以方便的在手机上查看 GitHub 的相关内容，扫描下方二维码就可以方便查看这个教程了~

![image](https://user-images.githubusercontent.com/4994339/57141874-dcc3b180-6ded-11e9-844e-d812d8198a1c.png)

小程序是开源的，有任何问题和意见可以直接提 Issue 反馈：[GitHub Trending Hub](https://github.com/ZhuPeng/mp-githubtrending)

**Comment by net592** [comment]
👍赞

**Comment by net592** [comment]
不过不支持翻页，和导航，还是网页版体验好哈

**Comment by ZhuPeng** [comment]
是的，体验上还有很多可以优化的


> From WeChat Mini Programe: [GitHub Trending Hub](https://github.com/ZhuPeng/mp-githubtrending?openid=ooqTr4hMz05xwBHOU8VgokLyyoU0)

**Comment by gold-dream-teacher** [comment]
被封了呀
