### ISSUE TITLE
添加grafana图表时， 变量如何匹配？

### ISSUE THREAD

**Issue by ghost** [yunlzheng/prometheus-book#32]
up{instance="172.29.50.175:9256",region="ap-southeast-1"}
namedprocess_namegroup_num_procs{instance="172.29.50.175:9256",region="ap-southeast-1"}

我在同一服务器上安装了多个exporter，对应不同的端口。在grafana中我定义了$HOST变量为取出来instance IP， 在图表展示时，如果我只需要 9100端口，如 node_load1{instance=~"$HOST:9100"}，我对生成的query url进行解码，发现是 query=node_load1{instance=~"1.1.1.1|2.2.2.2|3.3.3.3:9100"}&start=1559125515&end=1559132715&step=15"这种格式，实际上我是想匹配 query=node_load1{instance=~"1.1.1.1:9100|2.2.2.2:9100|3.3.3.3:9100"}&start=1559125515&end=1559132715&step=15", 请问这种情况表达式如何写呢？

**Comment by yunlzheng** [comment]
Grafana里面的变量默认都是多选的形式，所以比如你的变量的HOST，会渲染成 a|b|c的形式，所以一般用的时候都是用 {label=~"$HOST"}的形式。

剩下的就是根据这个规则去写PromQL。

**Comment by yunlzheng** [comment]
@Green-unicorn 另外如果你希望是根据端口去做数据聚合，那应该在采集的时候就把端口作为监控指标的一个单独Label, 这个可以用relabel去处理。 这样grafana里面就可以直接用。
