### ISSUE TITLE
第二章理解时间序列

### ISSUE THREAD

**Issue by xuexiaoao** [yunlzheng/prometheus-book#5]
![image](https://user-images.githubusercontent.com/18185523/43032586-228679e2-8ced-11e8-8a46-b5d5e4e7a7f6.png)
其中以后面是不是少了什么词呐，比如_name
[点此直达](https://yunlzheng.gitbook.io/prometheus-book/parti-prometheus-ji-chu/di-2-zhang-tan-suo-promql/li-jie-shi-jian-xu-lie)

**Comment by yunlzheng** [comment]
恩，markdown格式问题，正确的是：以`__`作为前缀的标签，是系统保留的关键字。 以修正，谢谢反馈哈
