### ISSUE TITLE
Use  'apps/v1' to replace 'extensions/v1beta1' for example-app deployment

### ISSUE THREAD

**Issue by DasyDong** [yunlzheng/prometheus-book#68]
Since kubernetes latest version has reached 1.18,  in new Version we need  new apiVersion value 

Use  'apps/v1' to replace 'extensions/v1beta1' for example-app deployment

path : use-operator-manage-prometheus.md 

current:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-app
```

new:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
```

**Comment by tanjunchen** [comment]
+1
