### ISSUE TITLE
是否适用监控服务器某个端口下的Tomcat是否运行？

### ISSUE THREAD

**Issue by daijinghao** [yunlzheng/prometheus-book#7]
您好，需求是要能够知道某个服务器下的Tomcat是否运行，请问prometheus是否支持？支持的话是用node_exporter这个探针还是别的？

**Comment by custa** [comment]
@daijinghao 用 [blackbox-exporter](https://github.com/prometheus/blackbox_exporter)

**Comment by daijinghao** [comment]
@custa 谢谢，找到了tomcat_exporter，另外请教下，怎样修改node_exporter的端口，默认是9100，怎样改成别的？

**Comment by yunlzheng** [comment]
@daijinghao  tomcat_exporter 主要是在白盒监控的层面获取tomcat具体的运行时指标，建议还是可以配合blackbox-exporter从黑盒监控的角度去检查可用性。

node-exporter 可以从启动参数修改端口 --web.listen-address=":9100"

**Comment by daijinghao** [comment]
@yunlzheng 谢谢~昨天解决了，用的就是这个命令
